name: Build and Release Multi-Arch aws-mfa-go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "debug"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: false

jobs:
  release:
    name: Create Release and Attach Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Build Binary for Release
        run: |
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }} -a -ldflags="-s -w" -installsuffix cgo

      - name: Create Tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y.%m.%d-%H%M%S')
          echo "TAG_NAME=v${VERSION}" >> $GITHUB_ENV

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}
          path: aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: aws-mfa-go-*
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
