name: Release

on:
  push:
    tags:
      - 'v*'
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "debug"
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: "Environment to run tests against"
        type: environment
        required: false

jobs:
  release:
    name: Release and Push
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#release')
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Create version tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y.%m.%d')
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "TAG_NAME=v${VERSION}-${COMMIT_SHA}" >> $GITHUB_ENV
          echo "Created TAG_NAME=$TAG_NAME"

      - name: Build Binary for Release
        run: |
          BINARY_NAME=aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -v -o $BINARY_NAME -a -trimpath -ldflags="-s -w -X main.version=${{ env.TAG_NAME }}" -installsuffix cgo

      - name: Verify Binary and Calculate Checksum
        run: |
          BINARY_NAME=aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          echo "Verifying binary existence..."
          ls -la $BINARY_NAME
          sha256sum $BINARY_NAME > ${BINARY_NAME}.sha256

      - name: Upload Release Assets
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}*
          retention-days: 5

      - name: Create Release
        if: success() && github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: |
            aws-mfa-go-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
