name: Build and Release Multi-Arch aws-mfa-go Image to GitHub Container Registry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "debug"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: false

jobs:
  release:
    name: Create Release and Attach Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Build Binary for Release
        run: |
          CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=linux go build -o aws-mfa-go -a -ldflags="-s -w" -installsuffix cgo

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          files: aws-mfa-go
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
